# Configuration file for thingino-button

{
  "device": "/dev/input/event0",
  "configuration": {
    "KEY_ENTER": {
      "action": [
        {
          "step_num": 0,
          "prompt": "/usr/bin/play-voice \"检查网络请按KEY_1,下一步请按KEY_ENTER\"",
          "enter": "/usr/bin/play-voice \"进入下一步\"",
          "key1": "/usr/bin/checknet",
          "timeout": 2
        },
        {
          "step_num": 1,
          "prompt": "/usr/bin/play-voice \"这是第二步\"",
          "enter": "/usr/bin/play-voice \"进入第三步\"",
          "key1": "/usr/bin/action2",
          "timeout": 2
        },
        {
          "step_num": 2,
          "prompt": "/usr/bin/play-voice \"这是最后一步\"",
          "enter": "/usr/bin/action3",
          "key1": "/usr/bin/action2",
          "timeout": 2
        }
      ]
    },
    "KEY_1": {
      "action": "/usr/bin/checknet",
      "timeout": 2
    }
  }
}
